name: get-target-regions
description: Get target regions from SSM parameter store
inputs:
  ssm_param_name:
    description: SSM param name
    required: true
  ssm_param_region:
    description: SSM param region
    required: true
outputs:
  target_regions:
    description: Target regions as array (json string)
    value: ${{ steps.fetch_ssm_param.outputs.regions }}
runs:
  using: "composite"
  steps:
    - id: fetch_ssm_param
      run: >
        echo "regions=$(aws ssm get-parameter --name ${{ inputs.ssm_param_name }} --region ${{ inputs.ssm_param_region }} | jq -r '.Parameter.Value')" >> $GITHUB_OUTPUT
      shell: bash
